### ISSUE TITLE
dCorrs need to check n1>3 and n2>3

### ISSUE THREAD

**Issue by bowenli37** [andymckenzie/DGCA#14] opened 2024-03-21 08:05 UTC
Hi,

dCorrs need to check n1>3 and n2>3

```
dCorrs <- function (rho1, n1, rho2, n2, corrType = "pearson") 
{
    if (!(all.equal(length(rho1), length(n1), length(rho2), length(n2)))) 
        stop("All of the input vectors must be the same length.")
    zr1 = atanh(rho1)
    zr2 = atanh(rho2)
    if (corrType == "pearson") {
        diff12 = (zr2 - zr1)/sqrt((1/(n1 - 3)) + (1/(n2 - 3)))
    }
    if (corrType == "spearman") {
        diff12 = (zr2 - zr1)/sqrt((1.06/(n1 - 3)) + (1.06/(n2 - 
            3)))
    }
    return(diff12)
}
```

Here is my quick fix.

```
DGCA_dCorrs <- function (rho1, n1, rho2, n2, corrType = "pearson")
{
  if (!(all.equal(length(rho1), length(n1), length(rho2), length(n2))))
    stop("All of the input vectors must be the same length.")
  zr1 = atanh(rho1)
  zr2 = atanh(rho2)
  if (corrType == "pearson") {
    diff12 = (zr2 - zr1)/sqrt((1/(n1 - 3)) + (1/(n2 - 3)))
  }
  if (corrType == "spearman") {
    diff12 = (zr2 - zr1)/sqrt((1.06/(n1 - 3)) + (1.06/(n2 -
                                                         3)))
  }
  ## NaN is more appropriate than NA
  diff12[n1 <= 3 | n2 <= 3] <- NaN
  return(diff12)
}

```

**Comment by andymckenzie** [comment] 2024-03-24 03:27
Hello and thank you for using DGCA. Could you please provide a reproducible example showing how this is affecting your workflow using DGCA? This will help me to debug it. Thank you.

**Comment by bowenli37** [comment] 2024-03-25 01:55
Hi,

x has 10 samples of 2 groups 'a' and 'b', and 5 genes.

There are 2 missing values in group a's gene1, so there are only 3 effective samples, not enough for calculating spearman  variance.

gene2 and gene3 has a correlation -1 in group 'a'.

```
set.seed(123)
# 1. missing values
# 2. corr = -1
x <- rnorm(50) %>% matrix(10, 5)
x[1:2,1] <- NA
x[1:5, 2] <- -1 * x[1:5, 3]
g <- rep(c('a','b'), each =5) %>% as.factor
colnames(x) <- paste0('gene', 1:5)
group <- as.factor(g)
mm <- model.matrix(~ group + 0)
colnames(mm) <- levels(group)



res1 <- DGCA::ddcorAll(
    t(x), mm, compare = c('a', 'b'), corrType = 'spearman', 
    nPairs = 'all', adjust = 'fdr', nPerms = 0, sigThresh = 0.05
)
```

```
> x
            gene1      gene2      gene3       gene4       gene5
 [1,]          NA  1.0678237 -1.0678237  0.42646422 -0.69470698
 [2,]          NA  0.2179749 -0.2179749 -0.29507148 -0.20791728
 [3,]  1.55870831  1.0260044 -1.0260044  0.89512566 -1.26539635
 [4,]  0.07050839  0.7288912 -0.7288912  0.87813349  2.16895597
 [5,]  0.12928774  0.6250393 -0.6250393  0.82158108  1.20796200
 [6,]  1.71506499  1.7869131 -1.6866933  0.68864025 -1.12310858
 [7,]  0.46091621  0.4978505  0.8377870  0.55391765 -0.40288484
 [8,] -1.26506123 -1.9666172  0.1533731 -0.06191171 -0.46665535
 [9,] -0.68685285  0.7013559 -1.1381369 -0.30596266  0.77996512
[10,] -0.44566197 -0.4727914  1.2538149 -0.38047100 -0.08336907
> res1
   Gene1 Gene2 a_cor    a_pVal b_cor    b_pVal zScoreDiff     pValDiff pValDiff_adj Classes
1  gene2 gene3  -1.0 0.0000000  -0.7 0.1881204 16.9985708 8.414656e-65 6.731725e-64     -/0
6  gene2 gene5  -0.5 0.3910022  -0.1 0.8728886  0.4360790 6.627794e-01 1.000000e+00  NonSig
4  gene3 gene4  -0.4 0.5046316  -0.6 0.2847570 -0.2617598 7.935066e-01 1.000000e+00  NonSig
2  gene3 gene5   0.5 0.3910022   0.4 0.5046316 -0.1220491 9.028602e-01 1.000000e+00  NonSig
5  gene2 gene4   0.4 0.0000000   0.5 0.3910022  0.1220491 9.028602e-01 1.000000e+00  NonSig
7  gene1 gene2   0.5 0.6666667   0.7 0.1881204  0.0000000 1.000000e+00 1.000000e+00  NonSig
8  gene1 gene3  -0.5 0.6666667  -0.2 0.7470601  0.0000000 1.000000e+00 1.000000e+00  NonSig
9  gene1 gene4   0.5 0.6666667   0.6 0.2847570  0.0000000 1.000000e+00 1.000000e+00  NonSig
3  gene1 gene5  -1.0 0.0000000  -0.4 0.5046316        NaN          NaN          NaN  NonSig
10  <NA>  <NA>    NA        NA    NA        NA         NA           NA           NA  NonSig
```

In matCorSig, corrs is a vector (length same as upper.tri) but used as indices for pvals.
```
function (corrs, nsamp, secondMat = FALSE) 
{
    if (!secondMat) {
        pvals = matrix(NA, nrow = nrow(corrs), ncol = ncol(corrs))
        corrs = corrs[upper.tri(corrs)]
        nsamp = nsamp[upper.tri(nsamp)]
        df = nsamp - 2
        pvals_upper = 2 * (1 - pt(abs(corrs) * sqrt(df)/sqrt(1 - 
            corrs^2), df))

        # debuger is here
        pvals[upper.tri(pvals)] = pvals_upper
        pvals[abs(corrs) == 1] = 0
    }
    else {
        df = nsamp - 2
        pvals = matrix(2 * (1 - pt(abs(corrs) * sqrt(df)/sqrt(1 - 
            corrs^2), df)), nrow = nrow(corrs))
        pvals[abs(corrs) == 1] = 0
    }
    return(pvals)
}

## debuger is at pvals[upper.tri(pvals)] = pvals_upper
Browse[5]> pvals
     [,1]      [,2]      [,3]      [,4]      [,5]
[1,]   NA 0.6666667 0.6666667 0.6666667 0.0000000
[2,]   NA        NA 0.0000000 0.5046316 0.3910022
[3,]   NA        NA        NA 0.5046316 0.3910022
[4,]   NA        NA        NA        NA 0.8728886
[5,]   NA        NA        NA        NA        NA
Browse[5]> corrs
 [1]  0.5 -0.5 -1.0  0.5  0.4 -0.4 -1.0 -0.5  0.5 -0.1
```

In dCorrs, numerical error at -1 (type double) can lead to wrong result, as shown in rho1. There are two -1.0, but the first -1 gives a atanh value of -18.3684003, the second one -Inf. So -1 and 1 should both be truncated.

```
Browse[6]> rho1
 [1]  0.5 -0.5 -1.0  0.5  0.4 -0.4 -1.0 -0.5  0.5 -0.1
Browse[6]> rho1 == -1
 [1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE
Browse[6]> rho2
 [1]  0.7 -0.2 -0.7  0.6  0.5 -0.6 -0.4 -0.1  0.4 -0.8
Browse[6]> zr1
 [1]   0.5493061  -0.5493061 -18.3684003   0.5493061   0.4236489  -0.4236489        -Inf  -0.5493061   0.5493061  -0.1003353
Browse[6]> zr2
 [1]  0.8673005 -0.2027326 -0.8673005  0.6931472  0.5493061 -0.6931472 -0.4236489 -0.1003353  0.4236489 -1.0986123
```

In dcTopPairs, sort removed NA and NaN in pValDiff.

```
pValDiff = slot(dcObject, "PValDiff")
sorted = sort(pValDiff, index.return = 1)
sorted_pvals = sorted$x

Browse[3]> pValDiff
     [,1] [,2]         [,3]      [,4]      [,5]
[1,]   NA    1 1.000000e+00 1.0000000       NaN
[2,]   NA   NA 8.414656e-65 0.9028602 0.6627794
[3,]   NA   NA           NA 0.7935066 0.9028602
[4,]   NA   NA           NA        NA 0.3322398
[5,]   NA   NA           NA        NA        NA
Browse[3]> 
debug: sorted_pvals = sorted$x
Browse[3]> sorted
$x
[1] 8.414656e-65 3.322398e-01 6.627794e-01 7.935066e-01 9.028602e-01 9.028602e-01 1.000000e+00 1.000000e+00 1.000000e+00

$ix
[1] 3 9 7 6 5 8 1 2 4
```

**Comment by andymckenzie** [comment] 2024-12-16 21:56
Thank you @bowenli37 for identifying these edge cases and providing such a thorough example. After reviewing the package's intended usage and existing safeguards, I'll be closing this issue because:

- Perfect correlations are already handled by the corr_cutoff parameter in pairwiseDCor (default 0.99)
- The n ≤ 3 case falls outside the intended use case of analyzing gene expression correlations with typical sample sizes

Closing this issue, but please feel free to create a new issue if you encounter related problems in practice. Thanks again for helping improve DGCA.

**Closed by andymckenzie** 2024-12-16 21:56 UTC
