### ISSUE TITLE
I am having issues using the parallelized version of ddMEGENA?

### ISSUE THREAD

**Issue by ashaypatel** [andymckenzie/DGCA#6] opened 2021-02-21 16:52 UTC
I know ddMEGENA is a wrapper for MEGENA. But I know you discuss how to use ddMEGENA in your DGCA Modules vingette. When I am running the parallelized version of ddMEGENA I am getting a warning:
`1: In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :scheduled cores 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 13, 16, 17, 19 did not deliver results, all values of the jobs will be affected`

Do you have a vignette/tips on how go use the parallelized version of ddMEGENA.  * I already have installed the doMC package *

Thanks,
Ashay

**Comment by andymckenzie** [comment] 2021-02-23 22:35
Hello Ashay, 

Thanks again for using DGCA. 

Unfortunately, it is somewhat difficult to debug this problem from the perspective of DGCA because the error message suggests that it is most likely a downstream problem with the parallelization framework, rather than the ddMEGENA() wrapper function. So, I will close the issue here as it is outside of the scope of DGCA. If you can post a reproducible example showing that this is a problem with the ddMEGENA() wrapper function rather than the downstream parallelization framework, I will re-open the issue and examine it further. 

That said, there are a couple of approaches that might be helpful: 

1. It is possible that you may able to run the code using the non-parallelized version of ddMEGENA(). Maybe this will be slower, but still eventually work. 

2. From a quick google search, here is one option that might be helpful: https://stackoverflow.com/questions/18330274/an-error-in-one-job-contaminates-others-with-mclapply

Best of luck with your work.

**Closed by andymckenzie** 2021-02-23 22:35 UTC
